"use client";

import React from "react";
import { Section } from "@/components/ui/Section";
import { Container } from "@/components/ui/Container";
import { Counter } from "@/components/ui/Counter";
import { Reveal } from "@/components/ui/Reveal";

export function StatsStrip() {
  return (
    <Section bg="dark" className="!bg-ink border-y border-brand-maroon/25 relative py-20 md:py-24 overflow-hidden">
      {/* Film grain noise texture */}
      <div className="noise-grain absolute inset-0 opacity-[0.035] pointer-events-none" aria-hidden="true" />

      {/* Subtle brand gradient background glows */}
      <div className="absolute inset-0 pointer-events-none z-0">
        <div className="absolute top-0 left-[-10%] w-[350px] h-[350px] rounded-full bg-brand-red/5 blur-[120px]" />
        <div className="absolute bottom-0 right-[-10%] w-[450px] h-[450px] rounded-full bg-brand-maroon/5 blur-[150px]" />
      </div>

      <Container className="relative z-10">
        {/* Eyebrow Label */}
        <div className="text-center mb-16">
          <span className="font-mono text-[10px] font-bold text-gold uppercase tracking-[0.3em]">
            04 / THE STATS
          </span>
        </div>

        <Reveal>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-12 lg:gap-0 divide-y sm:divide-y-0 lg:divide-x divide-white/10 lg:divide-white/5 border-b border-t border-white/5 py-12 mb-16">
            
            {/* Stat 1: 82% */}
            <div className="flex flex-col items-center text-center px-4 py-6 sm:py-4 lg:py-0">
              <span className="font-display font-black text-5xl sm:text-6xl text-white tracking-tight mb-4">
                <Counter value={82} suffix="%" />
              </span>
              <p className="text-xs font-mono uppercase tracking-widest text-slate-400 max-w-[200px]">
                Business Referrals
              </p>
              <p className="text-xs text-slate-500 font-sans mt-2 max-w-[220px]">
                of business owners report referrals as their primary channel.
              </p>
            </div>

            {/* Stat 2: ₹20,257 Cr */}
            <div className="flex flex-col items-center text-center px-4 py-6 sm:py-4 lg:py-0">
              <span className="font-display font-black text-5xl sm:text-6xl text-white tracking-tight mb-4 leading-none">
                <Counter value={20257} prefix="₹" suffix=" Cr" />
              </span>
              <p className="text-xs font-mono uppercase tracking-widest text-slate-400 max-w-[200px]">
                Revenue Passed
              </p>
              <p className="text-xs text-slate-500 font-sans mt-2 max-w-[220px]">
                of total business generated by BNI India members.
              </p>
            </div>

            {/* Stat 3: 355K+ */}
            <div className="flex flex-col items-center text-center px-4 py-6 sm:py-4 lg:py-0">
              <span className="font-display font-black text-5xl sm:text-6xl text-white tracking-tight mb-4">
                <Counter value={355} suffix="K+" />
              </span>
              <p className="text-xs font-mono uppercase tracking-widest text-slate-400 max-w-[200px]">
                Global Members
              </p>
              <p className="text-xs text-slate-500 font-sans mt-2 max-w-[220px]">
                collaborating across BNI chapters internationally.
              </p>
            </div>

            {/* Stat 4: 40+ */}
            <div className="flex flex-col items-center text-center px-4 py-6 sm:py-4 lg:py-0">
              <span className="font-display font-black text-5xl sm:text-6xl text-white tracking-tight mb-4">
                <Counter value={40} suffix="+" />
              </span>
              <p className="text-xs font-mono uppercase tracking-widest text-slate-400 max-w-[200px]">
                Indore Chapter
              </p>
              <p className="text-xs text-slate-500 font-sans mt-2 max-w-[220px]">
                active local business owners cooperating weekly.
              </p>
            </div>

          </div>
        </Reveal>

        {/* Forbes line */}
        <Reveal delay={0.2}>
          <div className="text-center font-sans">
            <span className="inline-block px-5 py-2 rounded-full bg-white/5 text-[10px] sm:text-xs text-gold font-bold uppercase tracking-widest border border-white/10">
              Ranked in Forbes&apos; Top 3 local business associations to belong to
            </span>
          </div>
        </Reveal>
      </Container>
    </Section>
  );
}
