"use client";

import React from "react";
import { Section } from "@/components/ui/Section";
import { Container } from "@/components/ui/Container";
import { Counter } from "@/components/ui/Counter";
import { Reveal } from "@/components/ui/Reveal";

/**
 * StatsStrip component: A high-impact stats band with a rich dark brand-maroon background.
 * Uses count-up animations for key statistics, bordered by thin gold grids.
 */
export function StatsStrip() {
  return (
    <Section bg="dark" className="!bg-[#630a10] border-y border-gold/20 relative py-16 md:py-20 overflow-hidden">
      {/* Decorative subtle light overlays */}
      <div className="absolute inset-0 pointer-events-none z-0">
        <div className="absolute top-0 left-[-10%] w-[300px] h-[300px] rounded-full bg-white/5 blur-2xl" />
        <div className="absolute bottom-0 right-[-10%] w-[450px] h-[450px] rounded-full bg-black/25 blur-3xl" />
      </div>

      <Container className="relative z-10">
        <Reveal>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-12 md:gap-0 divide-y md:divide-y-0 md:divide-x divide-gold/30 mb-12">
            
            {/* Stat 1: 82% */}
            <div className="flex flex-col items-center text-center px-6 py-6 md:py-0">
              <span className="font-heading font-extrabold text-5xl md:text-6xl text-white tracking-tight mb-3">
                <Counter value={82} suffix="%" />
              </span>
              <p className="text-sm font-sans text-cream/90 max-w-[240px] leading-relaxed">
                of business owners report most of their business comes from referrals.
              </p>
            </div>

            {/* Stat 2: ₹20,257 Cr */}
            <div className="flex flex-col items-center text-center px-6 py-6 md:py-0">
              <span className="font-heading font-extrabold text-5xl md:text-6xl text-white tracking-tight mb-3">
                <Counter value={20257} prefix="₹" suffix=" Cr" />
              </span>
              <p className="text-sm font-sans text-cream/90 max-w-[240px] leading-relaxed">
                of business generated by BNI India members (2021–22).
              </p>
            </div>

            {/* Stat 3: 355K+ */}
            <div className="flex flex-col items-center text-center px-6 py-6 md:py-0">
              <span className="font-heading font-extrabold text-5xl md:text-6xl text-white tracking-tight mb-3">
                <Counter value={355} suffix="K+" />
              </span>
              <p className="text-sm font-sans text-cream/90 max-w-[240px] leading-relaxed">
                BNI members worldwide collaborating across 77+ countries.
              </p>
            </div>

          </div>
        </Reveal>

        {/* Sub-label statement */}
        <Reveal delay={0.2}>
          <div className="text-center font-sans">
            <span className="inline-block px-4 py-1.5 rounded-full bg-black/15 text-[11px] sm:text-xs text-gold font-bold uppercase tracking-widest border border-gold/15">
              Ranked in Forbes&apos; Top 3 local business associations to belong to
            </span>
          </div>
        </Reveal>
      </Container>
    </Section>
  );
}
